### ISSUE TITLE
Better Structure

### ISSUE THREAD

**Issue by JollyJolli** [JollyJolli/formen.cc#7]
Hey there! So this is very simple! I want to move the CSS to /css/ and also the javascript, images and all that in this project, dont forget to redirect all files. Example: If in the HTML I use a image and is "image.png" and you move it to "/img/image-1.png" dont forget to change it also in the HTML.

**Thanks**.

**Comment by SahilShaw2004** [comment]
@JollyJolli  assign the task to me i will do it

**Comment by JollyJolli** [comment]
Yeah of course, thank you I really need this!

**Comment by SahilShaw2004** [comment]
One thing to ask should i remobe promo folder and placed it inside a single folder Images as well?

**Comment by JollyJolli** [comment]
Good question, I thing that is a good idea, so yes, /images/promo/etc

**Comment by SahilShaw2004** [comment]
PR send could you please see and tell me if it is ok if yes then kindly merge it and if no then tell me the changes you wants to see

**Comment by JollyJolli** [comment]
Done, thanks @SahilShaw2004
